### ISSUE TITLE
Can you clarify "In this code, we read offline 3D cuboid, the objects can be detected online"

### ISSUE THREAD

**Issue by Mechazo11** [benchun123/point-plane-object-SLAM#5]
Hi @benchun123,

Once again, thank you very much for open-sourcing your excellent work. 

Can you clarify what you meant by "In this code, **we read offline 3D cuboid**, the objects can be detected online." 

I understood the latter part of the statement i.e. pass bounding box and class label during runtime but why would you need to read the 3d cuboids offline? Aren't you generating them during run time?

With best,
@Mechazo11

**Comment by benchun123** [comment]
Hi @Mechazo11 

Thank you for following this work. As you can find in my code, [online method is disabled](https://github.com/benchun123/point-plane-object-SLAM/blob/e231a66155cebf71b58ff56cd02d8f4f300e4cb3/src/Tracking.cc#L2050). 

We can integrate the [monocular object detection](https://github.com/benchun123/monocular_object_detection) into this part to get an online SLAM system. Here we separate it into two parts because in this code, we focus on SLAM part. 

Best regards, 
Benchun Zhou

**Comment by Mechazo11** [comment]
@benchun123 thank you very much for clarifying this matter. This is very helpful.
